name: stylegan3
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow
  - scipy
  - requests
  - tqdm
  - matplotlib
  - imageio
  - pip:
    - imgui>=2.0.0
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - torch
