

IMPRESSION_PROMPTS = {
    "asian": (
        "an asian person's face",
        "a face that appears asian",
        "a portrait of a person perceived as asian",
        "a face with an east asian appearance",
        "an east asian person's face",
        "a southeast asian person's face",
        "a south asian person's face",
        "a central asian person's face",
        "a chinese person's face",
        "a japanese person's face",
        "a korean person's face",
        "a person with mixed asian ancestry",
        "a white person's face",
        "a black person's face",
        "a middle eastern person's face",
        "a hispanic person's face",
    ),
    "happy": (
        "a happy face",
        "a face with a happy expression",
        "a person who looks cheerful",
        "a joyful face",
        "a delighted person's face",
        "a contented person's face",
        "a smiling face",
        "a face with a broad smile",
        "a face with a subtle smile",
        "a person smiling with their mouth closed",
        "a person smiling with their teeth showing",
        "a face with smiling eyes",
        "a sad face",
        "an unhappy face",
        "a neutral facial expression",
        "a serious face",
    ),
}